import { RouteMeta } from '../../components/seo/RouteMeta'
import { siteUrl } from '../../lib/env'

const Authority = () => {
  return (
    <div className="container py-12">
      <RouteMeta
        title="Archival Authority & Citation Policy — Republic of Ambazonia"
        description="Canonical citation standards, archival permanence policy, and URL structure for the Federal Republic of Ambazonia institutional document archive."
        canonical={`${siteUrl}/about/authority`}
      />

      <div className="max-w-3xl mx-auto">
        <div className="h-px w-10 bg-gold-500 mb-6" />
        <h1 className="font-serif text-navy-900 text-3xl mb-4">
          Archival Authority &amp; Citation Policy
        </h1>
        <p className="text-sm font-sans text-navy-700/60 mb-12 leading-relaxed">
          This page documents the standards governing document permanence, citation formatting,
          and canonical URL structure within the Republic of Ambazonia institutional archive.
        </p>

        {/* Section 1: Archival Permanence */}
        <section className="mb-12" aria-labelledby="archival-permanence">
          <h2
            id="archival-permanence"
            className="font-serif text-navy-900 text-xl mb-3"
          >
            Archival Permanence
          </h2>
          <div className="h-px w-6 bg-gold-500 mb-6" />
          <div className="space-y-4 text-sm font-sans text-navy-700/75 leading-relaxed">
            <p>
              All documents held in this archive are assigned a permanent, immutable document
              number at the time of ingestion. This number does not change regardless of
              subsequent updates to the archive or its cataloguing system.
            </p>
            <p>
              Document numbers follow the format{' '}
              <code className="font-mono text-xs bg-slate-100 px-1.5 py-0.5 text-navy-700">
                ROA-YYYY-XXXX
              </code>
              , where <em>YYYY</em> denotes the document's year of record and <em>XXXX</em> is
              a zero-padded four-digit sequence within that year.
            </p>
            <p>
              Documents with no recorded year are catalogued under the reserved year group{' '}
              <code className="font-mono text-xs bg-slate-100 px-1.5 py-0.5 text-navy-700">
                0000
              </code>
              . The sequence within each year group is determined by ascending alphabetical
              order of document title and is stable across system builds.
            </p>
          </div>
        </section>

        {/* Section 2: Citation Policy */}
        <section className="mb-12" aria-labelledby="citation-policy">
          <h2
            id="citation-policy"
            className="font-serif text-navy-900 text-xl mb-3"
          >
            Citation Policy
          </h2>
          <div className="h-px w-6 bg-gold-500 mb-6" />
          <div className="space-y-4 text-sm font-sans text-navy-700/75 leading-relaxed">
            <p>
              Two citation formats are provided for each archived document: an institutional
              format for administrative and governmental reference, and an academic format
              conforming to standard bibliographic conventions.
            </p>

            <div className="border border-slate-200 bg-parchment-50 p-4 space-y-2">
              <p className="text-xs font-sans text-navy-700/45 uppercase tracking-widest">
                Institutional Format
              </p>
              <p className="text-xs font-mono text-navy-700/65 leading-relaxed break-all">
                {'{Title} — {Year} — {Category} — Document ID: {id} — Canonical: {url} — Accessed: {YYYY-MM-DD}'}
              </p>
            </div>

            <div className="border border-slate-200 bg-parchment-50 p-4 space-y-2">
              <p className="text-xs font-sans text-navy-700/45 uppercase tracking-widest">
                Academic Format
              </p>
              <p className="text-xs font-mono text-navy-700/65 leading-relaxed break-all">
                {'Republic of Ambazonia. "{Title}." {Year}. Document No. {ROA-YYYY-XXXX}. {Canonical URL}. Accessed {YYYY-MM-DD}.'}
              </p>
            </div>

            <p>
              Both formats include a canonical URL and an access date. Citations generated by
              this system reflect the date on which the document page was visited. When citing
              for archival or legal purposes, record the access date at the time of first
              retrieval.
            </p>
          </div>
        </section>

        {/* Section 3: Textual Normalization Policy */}
        <section className="mb-12" aria-labelledby="normalization-policy">
          <h2
            id="normalization-policy"
            className="font-serif text-navy-900 text-xl mb-3"
          >
            Textual Normalization Policy
          </h2>
          <div className="h-px w-6 bg-gold-500 mb-6" />
          <div className="space-y-4 text-sm font-sans text-navy-700/75 leading-relaxed">
            <p>
              Names and titles within this archive are standardized to their authoritative
              spelling at the archival layer. Where source documents or prior cataloguing
              contain transcription errors, the corrected form is applied to all metadata
              fields including titles, document identifiers, and citation output.
            </p>
            <p>
              When a name correction requires a change to a canonical document slug, a
              client-side redirect is maintained from the legacy slug to the corrected slug.
              This ensures that external references using the prior spelling remain
              resolvable without returning an error.
            </p>
            <p>
              The search and inquiry system applies the same normalization to user queries,
              mapping known legacy spellings to their canonical equivalents before matching
              against the document index. This preserves retrieval continuity for queries
              constructed from historical external references.
            </p>
          </div>
        </section>

        {/* Section 4: Canonical URL Structure */}
        <section className="mb-12" aria-labelledby="canonical-structure">
          <h2
            id="canonical-structure"
            className="font-serif text-navy-900 text-xl mb-3"
          >
            Canonical URL Structure
          </h2>
          <div className="h-px w-6 bg-gold-500 mb-6" />
          <div className="space-y-4 text-sm font-sans text-navy-700/75 leading-relaxed">
            <p>
              Each document is accessible at a single, authoritative URL of the form:
            </p>
            <div className="border border-slate-200 bg-parchment-50 px-4 py-3">
              <code className="text-xs font-mono text-navy-700/65 break-all">
                {siteUrl}/documents/{'{'}{'{'}document-id{'}'}{'}'}
              </code>
            </div>
            <p>
              Canonical URLs are lowercase, contain no trailing slashes, and use the
              document's stable identifier as the path segment. All variant URLs — including
              those with case differences, trailing slashes, or double slashes — are
              automatically redirected to the canonical form.
            </p>
            <p>
              The document identifier is derived from the source filename and does not change
              once assigned. External references and citations should use the canonical URL to
              ensure permanent, unambiguous access.
            </p>
          </div>
        </section>
      </div>
    </div>
  )
}

export default Authority
